#!/usr/bin/env python3
"""LK GMC P2A next online executor.

Scope: Merchant API v1 ProductInputs PATCH for dataSource 10636492695,
`productAttributes.googleProductCategory` + `productAttributes.productTypes` only,
using the approved pilot CSV generated by lk_gmc_p2a_next_online_preview_20260513.py.
Default dry-run. Apply requires exact Lucas approval text and creates private rollback.
"""
from __future__ import annotations
import argparse, csv, importlib.util, json, os, pathlib, time
from collections import Counter
from datetime import datetime, timezone
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[1]
P2_PATH = ROOT / 'scripts/lk_gmc_p2_category_product_type_executor_20260513.py'
PREVIEW_CSV = ROOT / 'reports/lk-gmc-2026-05-13-p2a-next-online-preview-pilot.csv'
RUN_STAMP = '2026-05-13-p2a-next-online-executor'
PUBLIC_JSON = ROOT / f'reports/lk-gmc-{RUN_STAMP}.json'
PUBLIC_MD = ROOT / f'reports/lk-gmc-{RUN_STAMP}.md'
PRIVATE_DIR = pathlib.Path('/opt/data/hermes_bruno_ingest/local_sql/lk_gmc_rollback_snapshots')
APPROVAL_TEXT_REQUIRED = 'Aprovo aplicar P2A next wave fresh misto em 250 produtos online no GMC via Merchant API v1, apenas googleProductCategory e productTypes, com rollback e verificação.'
DATA_SOURCE_ID = '10636492695'

def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()

def load_mod(path: pathlib.Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader
    spec.loader.exec_module(mod)
    return mod

def load_rows(limit: int) -> list[dict[str, Any]]:
    rows=[]
    with PREVIEW_CSV.open(encoding='utf-8') as f:
        for r in csv.DictReader(f):
            if limit and len(rows) >= limit: break
            pts=json.loads(r.get('suggested_productTypes') or '[]')
            cur_pts=json.loads(r.get('current_productTypes') or '[]')
            rows.append({**r, 'current_productTypes': cur_pts, 'suggested_productTypes': pts})
    return rows

def merchant_attrs(p2, mid: str, token: str, pid: str) -> dict[str, Any]:
    _name, encoded, *_ = p2.product_input_name(mid, pid)
    return (p2.merchant_product_get(mid, encoded, token).get('productAttributes') or {})

def patch_p2a(p2, mid: str, token: str, r: dict[str, Any]) -> dict[str, Any]:
    return p2.patch_category_product_types(mid, token, r['product_id'], r['suggested_googleProductCategory'], r['suggested_productTypes'])

def snapshot(records: list[dict[str, Any]]) -> pathlib.Path:
    PRIVATE_DIR.mkdir(parents=True, exist_ok=True); os.chmod(PRIVATE_DIR,0o700)
    path=PRIVATE_DIR / f'lk-gmc-{RUN_STAMP}-rollback-{datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")}.json'
    path.write_text(json.dumps({'generated_at':utc_now(),'scope':'P2A next online pilot: googleProductCategory + productTypes only','approval_text_required':APPROVAL_TEXT_REQUIRED,'records':records,'rollback_instruction':'Patch productAttributes.googleProductCategory/productTypes back to previous values after review if rollback needed.'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    os.chmod(path,0o600); return path

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--apply',action='store_true'); ap.add_argument('--approval-text',default=''); ap.add_argument('--limit',type=int,default=250); ap.add_argument('--verify-delay',type=int,default=120)
    args=ap.parse_args(); mode='apply' if args.apply else 'dry-run'
    if args.apply and args.approval_text != APPROVAL_TEXT_REQUIRED:
        raise RuntimeError('apply_blocked_missing_exact_approval_text: '+APPROVAL_TEXT_REQUIRED)
    p2=load_mod(P2_PATH,'p2_next')
    w=p2.import_w4(); audit=w.import_audit(); secrets=audit.load_doppler(); mid=secrets.get('MERCHANT_CENTER_ID_LK'); token=audit.google_access_token(audit.parse_service_account(secrets))
    rows=load_rows(args.limit)
    assessed=[]
    for r in rows:
        attrs=merchant_attrs(p2, mid, token, r['product_id'])
        current_gpc=attrs.get('googleProductCategory')
        current_pts=attrs.get('productTypes') or []
        eligible = r['product_id'].startswith('online:pt:BR:') and (current_gpc != r['suggested_googleProductCategory'] or current_pts != r['suggested_productTypes'])
        assessed.append({**r,'fresh_current_googleProductCategory':current_gpc,'fresh_current_productTypes':current_pts,'fresh_title':attrs.get('title'),'eligible':eligible})
        time.sleep(0.03)
    exec_results=[]; verify_results=[]; rollback=None
    if args.apply:
        selected=[r for r in assessed if r['eligible']]
        rollback=snapshot(selected)
        progress=PRIVATE_DIR / f'lk-gmc-{RUN_STAMP}-progress-{rollback.stem.rsplit("-",1)[-1]}.jsonl'
        with progress.open('w',encoding='utf-8') as f:
            os.chmod(progress,0o600)
            for r in selected:
                try:
                    resp=patch_p2a(p2, mid, token, r)
                    item={'product_id':r['product_id'],'execution_status':'patched_p2a_next_v1','product_input':resp.get('name'),'expected_googleProductCategory':r['suggested_googleProductCategory'],'expected_productTypes':r['suggested_productTypes']}
                except Exception as e:
                    item={'product_id':r['product_id'],'execution_status':'failed_patch_p2a_next_v1','error':str(e)[:1500]}
                    exec_results.append(item); f.write(json.dumps(item,ensure_ascii=False)+'\n'); f.flush(); break
                exec_results.append(item); f.write(json.dumps(item,ensure_ascii=False)+'\n'); f.flush(); time.sleep(0.2)
        if args.verify_delay: time.sleep(args.verify_delay)
        for item in exec_results:
            try:
                attrs=merchant_attrs(p2, mid, token, item['product_id'])
                match=(attrs.get('googleProductCategory')==item['expected_googleProductCategory'] and (attrs.get('productTypes') or [])==item['expected_productTypes'])
                verify_results.append({**item,'verify_status':'verified_merchant_product_get','actual_googleProductCategory':attrs.get('googleProductCategory'),'actual_productTypes':attrs.get('productTypes') or [],'match_expected':match})
            except Exception as e:
                verify_results.append({**item,'verify_status':'verify_failed','verify_error':str(e)[:1200]})
            time.sleep(0.03)
    summary={'mode':mode,'records_total':len(rows),'eligible':sum(1 for r in assessed if r['eligible']),'bucket_counts':{f'{k[0]} / {k[1]}':v for k,v in Counter((r['suggested_googleProductCategory'], (r['suggested_productTypes'] or [''])[0]) for r in assessed if r['eligible']).most_common()},'execution_results_summary':dict(Counter(x.get('execution_status') for x in exec_results)),'verify_results_summary':dict(Counter(x.get('verify_status') for x in verify_results)),'verified_match_expected':sum(1 for x in verify_results if x.get('match_expected'))}
    payload={'generated_at':utc_now(),'status':'apply_verified' if args.apply and summary['verified_match_expected']==len(exec_results) else ('apply_completed_needs_review' if args.apply else 'dry_run_ready'),'api':'Merchant API v1 ProductInputs PATCH','data_source':f'accounts/*/dataSources/{DATA_SOURCE_ID}','approval_required_for_apply':APPROVAL_TEXT_REQUIRED,'summary':summary,'private_rollback_snapshot_path':str(rollback) if rollback else None,'assessed_rows':assessed,'execution_results':exec_results,'verify_results':verify_results,'not_performed':['title_update','price_update','availability_update','image_or_link_update','merchant_delete','local_inventory_write','shopify_write','tiny_write','database_write','feed_fetch_or_upload','campaign_or_message_send']}
    PUBLIC_JSON.write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    lines=['# LK GMC P2A Next Online Executor — 2026-05-13','',f"Status: `{payload['status']}`",'', '## Escopo','- Somente online ProductInputs.','- Campos: `productAttributes.googleProductCategory` + `productAttributes.productTypes`.','- DataSource: `10636492695`.','', '## Resultado',f"- Mode: {mode}",f"- Records: {summary['records_total']}",f"- Eligible fresh: {summary['eligible']}",f"- Buckets: {summary['bucket_counts']}",f"- Execution: {summary['execution_results_summary']}",f"- Verify: {summary['verify_results_summary']}",f"- Match esperado: {summary['verified_match_expected']}/{len(verify_results)}",'', '## Approval text',f"`{APPROVAL_TEXT_REQUIRED}`",'', '## Não executado']
    lines += [f'- {x}' for x in payload['not_performed']]
    PUBLIC_MD.write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(json.dumps({'status':payload['status'],'summary':summary,'report':str(PUBLIC_MD),'rollback':str(rollback) if rollback else None},ensure_ascii=False,indent=2))
if __name__=='__main__': main()
